### ISSUE TITLE
Kawaii's Vrchat Mobile

### ISSUE THREAD

**Issue by Kawaiigirly** [fa0311/vrc_manager#103]
### OS

Android 12

### Device name

Samsung Galaxy S22 Ultra

### Country of origin of connection

English

### Where you downloaded the app

Github(GMS)

### Have you reinstalled it ?

Yes

### Bug description

UwU others are vrc are looking of secret

### Steps to reproduce

1. "Open Online Friends"

### Relevant error message output

```shell
You did like then
```

**Comment by fa0311** [comment]
Couldn't identify the problem.
I have a few questions
- (1) Does this problem still appear now?
- (2) If there is a log that is saved to the clipboard when the error dialog is displayed, please post it in its entirety.
- (3) Is there any friend who is missing any information (for example, there is a friend whose world is not displayed, or whose name is not displayed)?
