### ISSUE TITLE
Unexpected character

### ISSUE THREAD

**Issue by shizuon** [fa0311/vrc_manager#116]
### OS

Android 12

### Device name

Motorola edge s

### Country of origin of connection

Hong Kong

### Where you downloaded the app

Github(Windows)

### Have you reinstalled it ?

No, perhaps that won't be necessary.

### Bug description

{
     "exceptionType": "FormatException: Unexpected character (at character 1)\nerror code: 1020\n^\n",
     "version": "4.0.1",
     "deviceInfo": {
          "id": "SQ3A.220705.004",
          "host": "buildssd",
          "tags": "release-keys",
          "type": "user",
          "model": "moto g(100)",
          "board": "nio",
          "brand": "motorola",
          "device": "nio",
          "product": "nio_retail",
          "display": "SQ3A.220705.004",
          "hardware": "qcom",
          "androidId": null,
          "bootloader": "MBM-3.0-nio_retail-9376d694c3-220503",
          "version": {
               "baseOS": "",
               "sdkInt": 32,
               "release": "12",
               "codename": "REL",
               "incremental": "1664999054",
               "previewSdkInt": 0,
               "securityPatch": "2022-09-05"
          },
          "fingerprint": "motorola/nio_retail/nio:12/S1RTS32.41-20-16-1-3/22842-f0a4cf:user/release-keys",
          "manufacturer": "motorola",
          "supportedAbis": [
               "arm64-v8a",
               "armeabi-v7a",
               "armeabi"
          ],
          "systemFeatures": [
               "android.hardware.sensor.proximity",
               "com.verizon.hardware.telephony.lte",
               "android.software.adoptable_storage",
               "com.verizon.hardware.telephony.ehrpd",
               "android.hardware.sensor.accelerometer",
               "android.software.controls",
               "android.hardware.faketouch",
               "com.google.android.feature.D2D_CABLE_MIGRATION_FEATURE",
               "android.hardware.usb.accessory",
               "android.hardware.telephony.cdma",
               "android.software.backup",
               "android.hardware.touchscreen",
               "android.hardware.touchscreen.multitouch",
               "android.software.print",
               "android.software.activities_on_secondary_displays",
               "android.hardware.wifi.rtt",
               "com.google.android.feature.PIXEL_2017_EXPERIENCE",
               "android.software.voice_recognizers",
               "android.software.picture_in_picture",
               "android.hardware.fingerprint",
               "android.hardware.sensor.gyroscope",
               "android.hardware.audio.low_latency",
               "android.software.vulkan.deqp.level",
               "android.software.cant_save_state",
               "com.google.android.feature.PIXEL_2018_EXPERIENCE",
               "android.hardware.security.model.compatible",
               "com.motorola.camera3",
               "com.google.android.feature.PIXEL_2019_EXPERIENCE",
               "android.hardware.opengles.aep",
               "android.hardware.sensor.relative_humidity",
               "android.hardware.bluetooth",
               "android.hardware.camera.autofocus",
               "com.google.android.feature.GOOGLE_BUILD",
               "android.hardware.telephony.gsm",
               "android.hardware.telephony.ims",
               "android.software.incremental_delivery",
               "android.software.sip.voip",
               "android.software.opengles.deqp.level",
               "com.motorola.photoeditor",
               "com.google.android.apps.photos.NEXUS_PRELOAD",
               "android.hardware.usb.host",
               "android.hardware.audio.output",
               "android.hardware.camera.flash",
               "android.hardware.camera.front",
               "android.hardware.sensor.hifi_sensors",
               "android.hardware.se.omapi.uicc",
               "com.motorola.camera3.nio",
               "android.hardware.screen.portrait",
               "android.hardware.nfc",
               "com.google.android.feature.TURBO_PRELOAD",
               "android.hardware.sensor.ambient_temperature",
               "com.google.android.feature.PIXEL_2021_MIDYEAR_EXPERIENCE",
               "android.hardware.sensor.stepdetector",
               "android.software.home_screen",
               "android.hardware.microphone",
               "android.software.autofill",
               "android.software.securely_removes_users",
               "com.google.android.feature.PIXEL_EXPERIENCE",
               "android.hardware.bluetooth_le",
               "android.hardware.sensor.compass",
               "com.google.android.feature.GOOGLE_FI_BUNDLED",
               "android.hardware.touchscreen.multitouch.jazzhand",
               "android.hardware.sensor.barometer",
               "android.software.app_widgets",
               "com.google.android.feature.PIXEL_2020_MIDYEAR_EXPERIENCE",
               "android.software.input_methods",
               "android.hardware.sensor.light",
               "android.hardware.vulkan.version",
               "android.software.companion_device_setup",
               "android.software.device_admin",
               "com.google.android.feature.WELLBEING",
               "android.hardware.wifi.passpoint",
               "android.hardware.camera",
               "android.hardware.screen.landscape",
               "android.software.device_id_attestation",
               "com.google.android.feature.AER_OPTIMIZED",
               "android.hardware.ram.normal",
               "com.google.android.apps.photos.nexus_preload",
               "com.google.android.feature.PIXEL_2019_MIDYEAR_EXPERIENCE",
               "android.software.managed_users",
               "android.software.webview",
               "android.hardware.sensor.stepcounter",
               "android.hardware.camera.capability.manual_post_processing",
               "android.hardware.camera.any",
               "android.hardware.camera.capability.raw",
               "android.hardware.vulkan.compute",
               "com.google.android.apps.dialer.call_recording_audio",
               "android.software.connectionservice",
               "android.hardware.touchscreen.multitouch.distinct",
               "android.hardware.location.network",
               "android.software.cts",
               "android.software.sip",
               "android.hardware.camera.capability.manual_sensor",
               "android.software.app_enumeration",
               "com.google.android.apps.dialer.SUPPORTED",
               "android.hardware.camera.level.full",
               "android.software.game_service",
               "com.google.android.feature.GAME_OVERLAY",
               "android.hardware.wifi.direct",
               "android.software.live_wallpaper",
               "com.google.android.feature.GOOGLE_EXPERIENCE",
               "android.software.ipsec_tunnels",
               "com.google.android.feature.EXCHANGE_6_2",
               "android.hardware.audio.pro",
               "android.hardware.nfc.hcef",
               "android.hardware.nfc.uicc",
               "android.hardware.location.gps",
               "android.sofware.nfc.beam",
               "android.software.midi",
               "com.motorola.camera3.content.ai",
               "android.hardware.nfc.any",
               "android.hardware.nfc.hce",
               "com.google.android.feature.PIXEL_2020_EXPERIENCE",
               "android.hardware.wifi",
               "android.hardware.location",
               "android.hardware.vulkan.level",
               "com.google.android.feature.PIXEL_2021_EXPERIENCE",
               "com.google.android.feature.QUICK_TAP",
               "android.software.secure_lock_screen",
               "android.hardware.biometrics.face",
               "android.hardware.telephony",
               "android.software.file_based_encryption",
               null
          ],
          "isPhysicalDevice": true,
          "supported32BitAbis": [
               "armeabi-v7a",
               "armeabi"
          ],
          "supported64BitAbis": [
               "arm64-v8a"
          ]
     },
     "error": "FormatException: Unexpected character (at character 1)\nerror code: 1020\n^\n",
     "message": "Unexpected character"
}

### Steps to reproduce

1. Open favorite worlds
2.it happens.

**Comment by shizuon** [comment]
yes, it occurs when i have a world which changed it status from public to private
but after deleted it, it solved.

**Comment by shizuon** [comment]
It really solved but i think it still should be a bug cause at least those worlds should display as "deleted" or something else not the application itself just report it as a bug, it would make user confused.

**Comment by fa0311** [comment]
This will be fixed in v5.0.0, which is under development.
We will let you know if we make progress.
